import { faAngleDoubleLeft } from '@fortawesome/pro-regular-svg-icons/faAngleDoubleLeft';
import { faAngleDoubleRight } from '@fortawesome/pro-regular-svg-icons/faAngleDoubleRight';
import { faBars } from '@fortawesome/pro-regular-svg-icons/faBars';
import { faArrowUp } from '@fortawesome/pro-regular-svg-icons/faArrowUp';
import { faArrowDown } from '@fortawesome/pro-regular-svg-icons/faArrowDown';
import { faFileDownload } from '@fortawesome/pro-regular-svg-icons/faFileDownload';
import { faTrashUndo } from '@fortawesome/pro-regular-svg-icons/faTrashUndo';
import { faHomeLg } from '@fortawesome/pro-regular-svg-icons/faHomeLg';
import { faArrowAltRight } from '@fortawesome/pro-regular-svg-icons/faArrowAltRight';
import { faArrowAltLeft } from '@fortawesome/pro-regular-svg-icons/faArrowAltLeft';
import { faSync } from '@fortawesome/pro-regular-svg-icons/faSync';
import { faSave } from '@fortawesome/pro-regular-svg-icons/faSave';
import { faCalendarAlt } from '@fortawesome/pro-regular-svg-icons/faCalendarAlt';
import { faHome } from '@fortawesome/pro-regular-svg-icons/faHome';
import { faTrashAlt } from '@fortawesome/pro-regular-svg-icons/faTrashAlt';
import { faAngleUp } from '@fortawesome/pro-regular-svg-icons/faAngleUp';
import { faWrench } from '@fortawesome/pro-regular-svg-icons/faWrench';
import { faAngleDown } from '@fortawesome/pro-regular-svg-icons/faAngleDown';
import { faTimes } from '@fortawesome/pro-regular-svg-icons/faTimes';
import { faPhone } from '@fortawesome/pro-regular-svg-icons/faPhone';
import { faEnvelope } from '@fortawesome/pro-regular-svg-icons/faEnvelope';
import { faFileExcel } from '@fortawesome/pro-regular-svg-icons/faFileExcel';
import { faUser } from '@fortawesome/pro-regular-svg-icons/faUser';
import { faFile } from '@fortawesome/pro-regular-svg-icons/faFile';
import { faFileWord } from '@fortawesome/pro-regular-svg-icons/faFileWord';
import { faFilePdf } from '@fortawesome/pro-regular-svg-icons/faFilePdf';
import { faLifeRing } from '@fortawesome/pro-regular-svg-icons/faLifeRing';
import { faArrowLeft } from '@fortawesome/pro-regular-svg-icons/faArrowLeft';
import { faCheck } from '@fortawesome/pro-regular-svg-icons/faCheck';
import { faStar } from '@fortawesome/pro-regular-svg-icons/faStar';
import { faBusinessTime } from '@fortawesome/pro-regular-svg-icons/faBusinessTime';
import { faEllipsisV } from '@fortawesome/pro-regular-svg-icons/faEllipsisV';
import { faAddressCard } from '@fortawesome/pro-regular-svg-icons/faAddressCard';
import { faBuilding } from '@fortawesome/pro-regular-svg-icons/faBuilding';
import { faInfoCircle } from '@fortawesome/pro-regular-svg-icons/faInfoCircle';
import { faQuestionCircle } from '@fortawesome/pro-regular-svg-icons/faQuestionCircle';
import { faEye } from '@fortawesome/pro-regular-svg-icons/faEye';
import { faReply } from '@fortawesome/pro-regular-svg-icons/faReply';
import { faReplyAll } from '@fortawesome/pro-regular-svg-icons/faReplyAll';
import { faForward } from '@fortawesome/pro-regular-svg-icons/faForward';
import { faPaperclip } from '@fortawesome/pro-regular-svg-icons/faPaperclip';
import { faStopwatch } from '@fortawesome/pro-regular-svg-icons/faStopwatch';
import { faLock } from '@fortawesome/pro-regular-svg-icons/faLock';
import { faClock } from '@fortawesome/pro-regular-svg-icons/faClock';
import { faAngleLeft } from '@fortawesome/pro-regular-svg-icons/faAngleLeft';
import { faAngleRight } from '@fortawesome/pro-regular-svg-icons/faAngleRight';
import { faEyeSlash } from '@fortawesome/pro-regular-svg-icons/faEyeSlash';
import { faSearch } from '@fortawesome/pro-regular-svg-icons/faSearch';
import { faArrowRight } from '@fortawesome/pro-regular-svg-icons/faArrowRight';
import { faFolderOpen } from '@fortawesome/pro-regular-svg-icons/faFolderOpen';
import { faCompactDisc } from '@fortawesome/pro-regular-svg-icons/faCompactDisc';
import { faAlarmClock } from '@fortawesome/pro-regular-svg-icons/faAlarmClock';
import { faRobot } from '@fortawesome/pro-regular-svg-icons/faRobot';
import { faGlasses } from '@fortawesome/pro-regular-svg-icons/faGlasses';
import { faCauldron } from '@fortawesome/pro-regular-svg-icons/faCauldron';
import { faFilter } from '@fortawesome/pro-regular-svg-icons/faFilter';
import { faCogs } from '@fortawesome/pro-regular-svg-icons/faCogs';
import { faExternalLink } from '@fortawesome/pro-regular-svg-icons/faExternalLink';
import { faPencil } from '@fortawesome/pro-regular-svg-icons/faPencil';
import { faFileArchive } from '@fortawesome/pro-regular-svg-icons/faFileArchive';
import { faCommentAlt } from '@fortawesome/pro-regular-svg-icons/faCommentAlt';
import { faHomeHeart } from '@fortawesome/pro-regular-svg-icons/faHomeHeart';
import { faCopy } from '@fortawesome/pro-regular-svg-icons/faCopy';
import { faPlug } from '@fortawesome/pro-regular-svg-icons/faPlug';
import { faEdit } from '@fortawesome/pro-regular-svg-icons/faEdit';
import { faCalendar } from '@fortawesome/pro-regular-svg-icons/faCalendar';
import { faClipboard } from '@fortawesome/pro-regular-svg-icons/faClipboard';
import { faStickyNote } from '@fortawesome/pro-regular-svg-icons/faStickyNote';
import { faShareAlt } from '@fortawesome/pro-regular-svg-icons/faShareAlt';
import { faDownload } from '@fortawesome/pro-regular-svg-icons/faDownload';
import { faLink } from '@fortawesome/pro-regular-svg-icons/faLink';
import { faCalculator } from '@fortawesome/pro-regular-svg-icons/faCalculator';
import { faFileAlt } from '@fortawesome/pro-regular-svg-icons/faFileAlt';
import { faEllipsisH } from '@fortawesome/pro-regular-svg-icons/faEllipsisH';
import { faStamp } from '@fortawesome/pro-regular-svg-icons/faStamp';
import { faPencilAlt } from '@fortawesome/pro-regular-svg-icons/faPencilAlt';
import { faTint } from '@fortawesome/pro-regular-svg-icons/faTint';
import { faToilet } from '@fortawesome/pro-regular-svg-icons/faToilet';
import { faTrash } from '@fortawesome/pro-regular-svg-icons/faTrash';
import { faShieldCheck } from '@fortawesome/pro-regular-svg-icons/faShieldCheck';
import { faUserLock } from '@fortawesome/pro-regular-svg-icons/faUserLock';
import { faUserTimes } from '@fortawesome/pro-regular-svg-icons/faUserTimes';
import { faExpandArrowsAlt } from '@fortawesome/pro-regular-svg-icons/faExpandArrowsAlt';
import { faPlus } from '@fortawesome/pro-regular-svg-icons/faPlus';
import { faListUl } from '@fortawesome/pro-regular-svg-icons/faListUl';
import { faMapMarkerAlt } from '@fortawesome/pro-regular-svg-icons/faMapMarkerAlt';
import { faMap } from '@fortawesome/pro-regular-svg-icons/faMap';
import { faFlagUsa } from '@fortawesome/pro-regular-svg-icons/faFlagUsa';
import { faFlag } from '@fortawesome/pro-regular-svg-icons/faFlag';
import { faFlagCheckered } from '@fortawesome/pro-regular-svg-icons/faFlagCheckered';
import { faUserTag } from '@fortawesome/pro-regular-svg-icons/faUserTag';
import { faAlignCenter } from '@fortawesome/pro-regular-svg-icons/faAlignCenter';
import { faText } from '@fortawesome/pro-regular-svg-icons/faText';
import { faTag } from '@fortawesome/pro-regular-svg-icons/faTag';
import { faAlignLeft } from '@fortawesome/pro-regular-svg-icons/faAlignLeft';
import { faStream } from '@fortawesome/pro-regular-svg-icons/faStream';

export const library = {
  add: (icon, name) => {
    library[icon.iconName] = icon;
    if (name) {
      library[name] = icon;
    }
  }
};
library.add(faStream, 'faStream');
library.add(faMap, 'faMap');
library.add(faTag, 'faTag');
library.add(faUserTag, 'faUserTag');
library.add(faFlagUsa, 'faFlagUsa');
library.add(faFlag, 'faFlag');
library.add(faFlagCheckered, 'faFlagCheckered');
library.add(faMapMarkerAlt, 'faMapMarkerAlt');
library.add(faCalendarAlt, 'faCalendarAlt');
library.add(faHome, 'faHome');
library.add(faTrashAlt, 'faTrashAlt');
library.add(faAngleUp, 'faAngleUp');
library.add(faWrench, 'faWrench');
library.add(faAngleDown, 'faAngleDown');
library.add(faTimes, 'faTimes');
library.add(faPhone, 'faPhone');
library.add(faEnvelope, 'faEnvelope');
library.add(faFileExcel, 'faFileExcel');
library.add(faUser, 'faUser');
library.add(faFile, 'faFile');
library.add(faFileWord, 'faFileWord');
library.add(faFilePdf, 'faFilePdf');
library.add(faLifeRing, 'faLifeRing');
library.add(faArrowLeft, 'faArrowLeft');
library.add(faCheck, 'faCheck');
library.add(faStar, 'faStar');
library.add(faBusinessTime, 'faBusinessTime');
library.add(faEllipsisV, 'faEllipsisV');
library.add(faBuilding, 'faBuilding');
library.add(faInfoCircle, 'faInfoCircle');
library.add(faEye, 'faEye');
library.add(faBars, 'faBars');
library.add(faArrowUp, 'faArrowUp');
library.add(faArrowDown, 'faArrowDown');
library.add(faEllipsisH, 'faEllipsisH');
library.add(faReply, 'faReply');
library.add(faReplyAll, 'faReplyAll');
library.add(faForward, 'faForward');
library.add(faPaperclip, 'faPaperclip');
library.add(faStopwatch, 'faStopwatch');
library.add(faLock, 'faLock');
library.add(faClock, 'faClock');
library.add(faAngleLeft, 'faAngleLeft');
library.add(faAngleRight, 'faAngleRight');
library.add(faEyeSlash, 'faEyeSlash');
library.add(faSearch, 'faSearch');
library.add(faArrowRight, 'faArrowRight');
library.add(faFolderOpen, 'faFolderOpen');
library.add(faCompactDisc, 'faCompactDisc');
library.add(faAlarmClock, 'faAlarmClock');
library.add(faRobot, 'faRobot');
library.add(faGlasses, 'faGlasses');
library.add(faCauldron, 'faCauldron');
library.add(faFileAlt, 'faFileAlt');
library.add(faFileDownload, 'faFileDownload');
library.add(faSave, 'faSave');
library.add(faTrashUndo, 'faTrashUndo');
library.add(faTrash, 'faTrash');
library.add(faHomeLg, 'faHomeLg');
library.add(faSync, 'faSync');
library.add(faFilter, 'faFilter');
library.add(faCogs, 'faCogs');
library.add(faExternalLink, 'faExternalLink');
library.add(faPencil, 'faPencil');
library.add(faFileArchive, 'faFileArchive');
library.add(faCommentAlt, 'faCommentAlt');
library.add(faHomeHeart, 'faHomeHeart');
library.add(faCopy, 'faCopy');
library.add(faPlug, 'faPlug');
library.add(faEdit, 'faEdit');
library.add(faCalendar, 'faCalendar');
library.add(faClipboard, 'faClipboard');
library.add(faStickyNote, 'faStickyNote');
library.add(faShareAlt, 'faShareAlt');
library.add(faAddressCard, 'faAddressCard');
library.add(faDownload, 'faDownload');
library.add(faLink, 'faLink');
library.add(faCalculator, 'faCalculator');
library.add(faStamp, 'faStamp');
library.add(faPencilAlt, 'faPencilAlt');
library.add(faTint, 'faTint');
library.add(faToilet, 'faToilet');
library.add(faShieldCheck, 'faShieldCheck');
library.add(faUserLock, 'faUserLock');
library.add(faUserTimes, 'faUserTimes');
library.add(faArrowAltLeft, 'faArrowAltLeft');
library.add(faArrowAltRight, 'faArrowAltRight');
library.add(faAngleDoubleLeft, 'faAngleDoubleLeft');
library.add(faAngleDoubleRight, 'faAngleDoubleRight');
library.add(faExpandArrowsAlt, 'faExpandArrowsAlt');
library.add(faPlus, 'faPlus');
library.add(faListUl, 'faListUl');
library.add(faAlignCenter, 'faAlignCenter');
library.add(faText, 'faText');
library.add(faAlignLeft, 'faAlignLeft');
library.add(faQuestionCircle, 'faQuestionCircle');
